name: Publish to nuget

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Package & Publish template
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: artifacts

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: Publish to NuGet
        run: nuget push artifacts/*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
