name: Build and Test .NET Library

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Add .NET Tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Library
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests with Code Coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Convert Coverage to JSON
        run: |
          reportgenerator \
            -reports:${{ github.workspace }}/tests/TestResults/**/*coverage.cobertura.xml \
            -targetdir:${{ github.workspace }}/tests/coverage-report \
            -reporttypes:JsonSummary

      - name: Extract Coverage Percentage
        id: extract-coverage
        run: |
          echo "Reading coverage percentage..."
          cat ${{ github.workspace }}/tests/coverage-report/Summary.json
          COVERAGE=$(jq .summary.linecoverage ${{ github.workspace }}/tests/coverage-report/Summary.json)
          echo "coverage=$COVERAGE"
          echo "coverage=$COVERAGE" >> $GITHUB_ENV
